/* Карты, объекты, зоны и точки спавна.
 * Новая карта: добавьте объект в MAPS и точки в SPAWNS — движок подхватит сам.
 */
(function (g) {
  "use strict";

  g.OBJECTS = {
    frog: { id: "frog", name: "Лягушка", category: "animals", src: "assets/objects/frog.png", size: 74, zones: ["water", "pond", "reeds", "puddle", "grass"] },
    duck: { id: "duck", name: "Утка", category: "animals", src: "assets/objects/duck.png", size: 80, zones: ["water", "pond", "reeds", "stream"] },
    cat: { id: "cat", name: "Кот", category: "animals", src: "assets/objects/cat.png", size: 78, zones: ["house", "fence", "bench", "entrance", "shade"] },
    hedgehog: { id: "hedgehog", name: "Ёж", category: "animals", src: "assets/objects/hedgehog.png", size: 70, zones: ["grass", "bushes", "trees", "stump", "leaves"] },
    squirrel: { id: "squirrel", name: "Белка", category: "animals", src: "assets/objects/squirrel.png", size: 72, zones: ["trees", "park", "stump", "fence"] },
    butterfly: { id: "butterfly", name: "Бабочка", category: "animals", src: "assets/objects/butterfly.png", size: 62, zones: ["flowers", "garden", "grass", "park"] },
    owl: { id: "owl", name: "Сова", category: "animals", src: "assets/objects/owl.png", size: 76, zones: ["trees", "forest", "shed", "barn"] },
    fish: { id: "fish", name: "Рыбка", category: "animals", src: "assets/objects/fish.png", size: 68, zones: ["water", "pond", "bucket-water", "trough", "stream"] },
    goose: { id: "goose", name: "Гусь", category: "animals", src: "assets/objects/goose.png", size: 82, zones: ["water", "pond", "reeds", "grass", "pens"] },
    ball: { id: "ball", name: "Мяч", category: "toys", src: "assets/objects/ball.png", size: 64, zones: ["playground", "grass", "bench", "swing", "path"] },
    teddy: { id: "teddy", name: "Плюшевый мишка", category: "toys", src: "assets/objects/teddy.png", size: 80, zones: ["playground", "bench", "tent", "swing", "picnic"] },
    doll: { id: "doll", name: "Кукла", category: "toys", src: "assets/objects/doll.png", size: 78, zones: ["playground", "bench", "stall", "swing"] },
    toy_car: { id: "toy_car", name: "Машинка", category: "toys", src: "assets/objects/toy_car.png", size: 72, zones: ["path", "playground", "pavement", "dirt", "entrance"] },
    balloon: { id: "balloon", name: "Шарик", category: "toys", src: "assets/objects/balloon.png", size: 78, zones: ["playground", "park", "stall", "fence", "awning"] },
    dino: { id: "dino", name: "Динозаврик", category: "toys", src: "assets/objects/dino.png", size: 74, zones: ["playground", "grass", "tent", "bench"] },
    rubber_duck: { id: "rubber_duck", name: "Игрушечная уточка", category: "toys", src: "assets/objects/rubber_duck.png", size: 66, zones: ["water", "pond", "puddle", "trough", "playground"] },
    spinning_top: { id: "spinning_top", name: "Юла", category: "toys", src: "assets/objects/spinning_top.png", size: 60, zones: ["playground", "path", "bench", "pavement"] },
    toy_boat: { id: "toy_boat", name: "Кораблик", category: "toys", src: "assets/objects/toy_boat.png", size: 72, zones: ["water", "pond", "stream", "puddle"] },
    shovel: { id: "shovel", name: "Лопата", category: "tools", src: "assets/objects/shovel.png", size: 88, zones: ["garden", "dirt", "barn", "shed", "fields"] },
    pitchfork: { id: "pitchfork", name: "Вилы", category: "tools", src: "assets/objects/pitchfork.png", size: 90, zones: ["hay", "barn", "shed", "pens"] },
    rake: { id: "rake", name: "Грабли", category: "tools", src: "assets/objects/rake.png", size: 88, zones: ["garden", "yard", "dirt", "grass", "fields"] },
    bucket: { id: "bucket", name: "Ведро", category: "tools", src: "assets/objects/bucket.png", size: 70, zones: ["well", "barn", "trough", "water", "garden", "bucket-water"] },
    flashlight: { id: "flashlight", name: "Фонарик", category: "tools", src: "assets/objects/flashlight.png", size: 64, zones: ["tent", "shed", "barn", "entrance", "bench"] },
    watering_can: { id: "watering_can", name: "Лейка", category: "tools", src: "assets/objects/watering_can.png", size: 74, zones: ["garden", "flowers", "beds", "well"] },
    hammer: { id: "hammer", name: "Молоток", category: "tools", src: "assets/objects/hammer.png", size: 70, zones: ["shed", "barn", "crate-zone", "fence"] },
    rope: { id: "rope", name: "Верёвка", category: "tools", src: "assets/objects/rope.png", size: 68, zones: ["barn", "shed", "cart", "pens", "stall"] },
    crate: { id: "crate", name: "Ящик", category: "farm", src: "assets/objects/crate.png", size: 72, zones: ["crate-zone", "barn", "stall", "cart", "dirt"] },
    mushroom: { id: "mushroom", name: "Гриб", category: "nature", src: "assets/objects/mushroom.png", size: 64, zones: ["trees", "forest", "stump", "grass", "rocks"] },
    apple: { id: "apple", name: "Яблоко", category: "food", src: "assets/objects/apple.png", size: 58, zones: ["picnic", "table", "stall", "produce", "trees", "basket-zone"] },
    lemonade: { id: "lemonade", name: "Лимонад", category: "food", src: "assets/objects/lemonade.png", size: 70, zones: ["picnic", "table", "bench", "stall"] },
    key: { id: "key", name: "Ключ", category: "items", src: "assets/objects/key.png", size: 58, zones: ["entrance", "bench", "fence", "stall", "well"] },
    boot: { id: "boot", name: "Сапог", category: "items", src: "assets/objects/boot.png", size: 70, zones: ["puddle", "barn", "entrance", "dirt", "porch"] },
    hat: { id: "hat", name: "Шляпа", category: "items", src: "assets/objects/hat.png", size: 72, zones: ["bench", "picnic", "stall", "hay", "fence"] },
    basket: { id: "basket", name: "Корзина", category: "items", src: "assets/objects/basket.png", size: 76, zones: ["stall", "picnic", "garden", "produce", "cart"] },
    flower: { id: "flower", name: "Цветок", category: "nature", src: "assets/objects/flower.png", size: 68, zones: ["garden", "flowers", "park", "stall", "beds"] },
    jar: { id: "jar", name: "Баночка", category: "items", src: "assets/objects/jar.png", size: 62, zones: ["table", "stall", "picnic", "produce"] },
    golden_key: { id: "golden_key", name: "Золотой ключ", category: "rare", src: "assets/objects/golden_key.png", size: 64, rare: true, zones: ["entrance", "well", "stall", "rocks", "fountain", "shed"] },
    shell: { id: "shell", name: "Ракушка", category: "nature", src: "assets/objects/shell.png", size: 60, zones: ["water", "pond", "sandbox", "puddle", "stream"] },
    lantern: { id: "lantern", name: "Фонарь", category: "items", src: "assets/objects/lantern.png", size: 72, zones: ["lamps", "tent", "entrance", "bench", "stall", "path"] },
  };

  g.MAPS = {
    village: {
      id: "village",
      name: "Деревня",
      src: "assets/maps/village.jpg",
      tint: "#6b8f4e",
    },
    park: {
      id: "park",
      name: "Парк",
      src: "assets/maps/park.jpg",
      tint: "#5e8a62",
    },
    forest: {
      id: "forest",
      name: "Лес",
      src: "assets/maps/forest.jpg",
      tint: "#3f6b45",
    },
    farm: {
      id: "farm",
      name: "Ферма",
      src: "assets/maps/farm.jpg",
      tint: "#7a8f45",
    },
    yard: {
      id: "yard",
      name: "Двор",
      src: "assets/maps/yard.jpg",
      tint: "#6d7a70",
    },
    market: {
      id: "market",
      name: "Ярмарка",
      src: "assets/maps/market.jpg",
      tint: "#b07a4a",
    },
  };

  /* Точки спавна: нормализованные x/y (0..1) + зоны.
     Предмет появляется только в точке, чьи зоны пересекаются с зонами предмета. */
  g.SPAWNS = {
    village: [
      { id: "v-pond-1", nx: 0.20, ny: 0.58, zones: ["water", "pond", "reeds"] },
      { id: "v-pond-2", nx: 0.16, ny: 0.66, zones: ["water", "pond", "reeds"] },
      { id: "v-reeds", nx: 0.27, ny: 0.62, zones: ["reeds", "grass", "pond"] },
      { id: "v-puddle-1", nx: 0.34, ny: 0.76, zones: ["puddle", "path", "grass"] },
      { id: "v-puddle-2", nx: 0.46, ny: 0.80, zones: ["puddle", "path"] },
      { id: "v-garden-1", nx: 0.12, ny: 0.82, zones: ["garden", "beds", "flowers"] },
      { id: "v-garden-2", nx: 0.22, ny: 0.84, zones: ["garden", "beds", "dirt"] },
      { id: "v-well", nx: 0.40, ny: 0.54, zones: ["well", "path", "house"] },
      { id: "v-coop", nx: 0.33, ny: 0.46, zones: ["coop", "grass", "house"] },
      { id: "v-bushes-l", nx: 0.08, ny: 0.48, zones: ["bushes", "trees", "shade"] },
      { id: "v-bushes-t", nx: 0.18, ny: 0.38, zones: ["bushes", "trees"] },
      { id: "v-barn-door", nx: 0.58, ny: 0.48, zones: ["barn", "dirt", "house"] },
      { id: "v-barn-side", nx: 0.64, ny: 0.42, zones: ["barn", "shed"] },
      { id: "v-hay", nx: 0.76, ny: 0.50, zones: ["hay", "barn"] },
      { id: "v-cart", nx: 0.68, ny: 0.58, zones: ["cart", "dirt", "barn"] },
      { id: "v-fence-r", nx: 0.88, ny: 0.64, zones: ["fence", "grass"] },
      { id: "v-fence-b", nx: 0.84, ny: 0.74, zones: ["fence", "grass"] },
      { id: "v-firewood", nx: 0.72, ny: 0.66, zones: ["firewood", "shed", "dirt"] },
      { id: "v-shed", nx: 0.50, ny: 0.34, zones: ["shed", "house"] },
      { id: "v-grass-c", nx: 0.48, ny: 0.66, zones: ["grass", "path"] },
      { id: "v-grass-r", nx: 0.90, ny: 0.80, zones: ["grass"] },
    ],
    park: [
      { id: "p-fountain", nx: 0.50, ny: 0.48, zones: ["fountain", "path"] },
      { id: "p-fountain-r", nx: 0.58, ny: 0.52, zones: ["fountain", "path", "bench"] },
      { id: "p-bench-l", nx: 0.36, ny: 0.50, zones: ["bench", "path", "shade"] },
      { id: "p-bench-r", nx: 0.66, ny: 0.46, zones: ["bench", "park"] },
      { id: "p-flowers-1", nx: 0.28, ny: 0.42, zones: ["flowers", "garden", "park"] },
      { id: "p-flowers-2", nx: 0.72, ny: 0.38, zones: ["flowers", "garden"] },
      { id: "p-flowers-3", nx: 0.44, ny: 0.62, zones: ["flowers", "grass"] },
      { id: "p-play", nx: 0.82, ny: 0.58, zones: ["playground", "swing"] },
      { id: "p-swing", nx: 0.78, ny: 0.50, zones: ["swing", "playground"] },
      { id: "p-sandbox", nx: 0.86, ny: 0.66, zones: ["sandbox", "playground"] },
      { id: "p-pond", nx: 0.22, ny: 0.70, zones: ["pond", "water", "reeds"] },
      { id: "p-pond-2", nx: 0.18, ny: 0.62, zones: ["water", "pond"] },
      { id: "p-trees-l", nx: 0.10, ny: 0.40, zones: ["trees", "shade", "bushes"] },
      { id: "p-trees-r", nx: 0.90, ny: 0.36, zones: ["trees", "park"] },
      { id: "p-picnic", nx: 0.38, ny: 0.72, zones: ["picnic", "table", "grass"] },
      { id: "p-path", nx: 0.52, ny: 0.78, zones: ["path", "grass"] },
      { id: "p-lamps", nx: 0.64, ny: 0.70, zones: ["lamps", "path"] },
      { id: "p-cart", nx: 0.30, ny: 0.56, zones: ["cart", "path", "picnic"] },
      { id: "p-hedge", nx: 0.12, ny: 0.78, zones: ["bushes", "grass"] },
      { id: "p-grass", nx: 0.70, ny: 0.80, zones: ["grass", "park"] },
    ],
    forest: [
      { id: "f-stream-1", nx: 0.42, ny: 0.70, zones: ["stream", "water", "rocks"] },
      { id: "f-stream-2", nx: 0.54, ny: 0.74, zones: ["stream", "water"] },
      { id: "f-stream-3", nx: 0.34, ny: 0.62, zones: ["stream", "reeds", "pond"] },
      { id: "f-tent", nx: 0.22, ny: 0.52, zones: ["tent", "campfire"] },
      { id: "f-fire", nx: 0.30, ny: 0.58, zones: ["campfire", "tent"] },
      { id: "f-stump-1", nx: 0.62, ny: 0.56, zones: ["stump", "trees", "grass"] },
      { id: "f-stump-2", nx: 0.70, ny: 0.48, zones: ["stump", "forest"] },
      { id: "f-rocks", nx: 0.48, ny: 0.58, zones: ["rocks", "stream"] },
      { id: "f-trees-l", nx: 0.12, ny: 0.42, zones: ["trees", "forest", "bushes"] },
      { id: "f-trees-c", nx: 0.50, ny: 0.36, zones: ["trees", "forest"] },
      { id: "f-trees-r", nx: 0.86, ny: 0.40, zones: ["trees", "forest"] },
      { id: "f-bushes", nx: 0.18, ny: 0.68, zones: ["bushes", "grass"] },
      { id: "f-clearing", nx: 0.58, ny: 0.64, zones: ["grass", "trail"] },
      { id: "f-trail", nx: 0.40, ny: 0.80, zones: ["trail", "grass"] },
      { id: "f-log", nx: 0.74, ny: 0.66, zones: ["stump", "trees", "grass"] },
      { id: "f-fern", nx: 0.78, ny: 0.78, zones: ["bushes", "grass", "forest"] },
      { id: "f-moss", nx: 0.66, ny: 0.38, zones: ["rocks", "trees"] },
      { id: "f-berry", nx: 0.28, ny: 0.40, zones: ["bushes", "trees"] },
    ],
    farm: [
      { id: "m-tractor", nx: 0.38, ny: 0.52, zones: ["tractor", "dirt"] },
      { id: "m-barn", nx: 0.62, ny: 0.40, zones: ["barn", "house"] },
      { id: "m-barn-door", nx: 0.58, ny: 0.50, zones: ["barn", "dirt"] },
      { id: "m-hay-1", nx: 0.72, ny: 0.54, zones: ["hay", "barn"] },
      { id: "m-hay-2", nx: 0.78, ny: 0.46, zones: ["hay"] },
      { id: "m-pens", nx: 0.22, ny: 0.58, zones: ["pens", "fence", "grass"] },
      { id: "m-barrels", nx: 0.48, ny: 0.60, zones: ["barrels", "crate-zone", "dirt"] },
      { id: "m-crates", nx: 0.54, ny: 0.66, zones: ["crate-zone", "dirt"] },
      { id: "m-trough", nx: 0.30, ny: 0.64, zones: ["trough", "water", "bucket-water", "pens"] },
      { id: "m-shed", nx: 0.84, ny: 0.42, zones: ["shed", "barn"] },
      { id: "m-fence", nx: 0.14, ny: 0.70, zones: ["fence", "grass"] },
      { id: "m-fields", nx: 0.70, ny: 0.72, zones: ["fields", "dirt", "garden"] },
      { id: "m-fields-2", nx: 0.86, ny: 0.68, zones: ["fields", "garden"] },
      { id: "m-silo", nx: 0.68, ny: 0.32, zones: ["silo", "barn"] },
      { id: "m-dirt", nx: 0.44, ny: 0.74, zones: ["dirt", "path"] },
      { id: "m-grass", nx: 0.18, ny: 0.80, zones: ["grass", "pens"] },
      { id: "m-wellish", nx: 0.36, ny: 0.42, zones: ["well", "dirt", "house"] },
    ],
    yard: [
      { id: "y-entrance", nx: 0.28, ny: 0.46, zones: ["entrance", "house", "porch"] },
      { id: "y-steps", nx: 0.32, ny: 0.54, zones: ["entrance", "pavement"] },
      { id: "y-car-1", nx: 0.58, ny: 0.58, zones: ["cars", "pavement"] },
      { id: "y-car-2", nx: 0.72, ny: 0.62, zones: ["cars", "pavement"] },
      { id: "y-bench", nx: 0.44, ny: 0.64, zones: ["bench", "shade"] },
      { id: "y-swing", nx: 0.84, ny: 0.50, zones: ["swing", "playground"] },
      { id: "y-play", nx: 0.88, ny: 0.58, zones: ["playground", "grass"] },
      { id: "y-puddle-1", nx: 0.40, ny: 0.74, zones: ["puddle", "pavement"] },
      { id: "y-puddle-2", nx: 0.52, ny: 0.78, zones: ["puddle", "path"] },
      { id: "y-bushes-l", nx: 0.12, ny: 0.58, zones: ["bushes", "shade"] },
      { id: "y-bushes-r", nx: 0.90, ny: 0.72, zones: ["bushes", "fence"] },
      { id: "y-lamps", nx: 0.36, ny: 0.40, zones: ["lamps", "path"] },
      { id: "y-dump", nx: 0.18, ny: 0.70, zones: ["dumpsters", "pavement"] },
      { id: "y-fence", nx: 0.78, ny: 0.78, zones: ["fence", "grass"] },
      { id: "y-flowers", nx: 0.24, ny: 0.38, zones: ["flowers", "house"] },
      { id: "y-path", nx: 0.48, ny: 0.50, zones: ["path", "pavement"] },
      { id: "y-grass", nx: 0.64, ny: 0.80, zones: ["grass"] },
    ],
    market: [
      { id: "k-stall-c", nx: 0.50, ny: 0.48, zones: ["stall", "table", "awning"] },
      { id: "k-stall-l", nx: 0.28, ny: 0.50, zones: ["stall", "produce", "awning"] },
      { id: "k-stall-r", nx: 0.72, ny: 0.46, zones: ["stall", "awning"] },
      { id: "k-produce", nx: 0.40, ny: 0.56, zones: ["produce", "table", "stall"] },
      { id: "k-flowers", nx: 0.22, ny: 0.58, zones: ["flowers", "stall", "garden"] },
      { id: "k-cart", nx: 0.62, ny: 0.62, zones: ["cart", "cobble", "path"] },
      { id: "k-barrels", nx: 0.34, ny: 0.66, zones: ["barrels", "crate-zone"] },
      { id: "k-crates", nx: 0.78, ny: 0.58, zones: ["crate-zone", "stall"] },
      { id: "k-cobble", nx: 0.50, ny: 0.72, zones: ["cobble", "path"] },
      { id: "k-table", nx: 0.58, ny: 0.52, zones: ["table", "picnic", "stall"] },
      { id: "k-awning", nx: 0.46, ny: 0.38, zones: ["awning", "stall"] },
      { id: "k-edge-l", nx: 0.12, ny: 0.64, zones: ["path", "cobble"] },
      { id: "k-edge-r", nx: 0.88, ny: 0.70, zones: ["path", "fence"] },
      { id: "k-front", nx: 0.48, ny: 0.82, zones: ["cobble", "path", "picnic"] },
      { id: "k-back", nx: 0.64, ny: 0.34, zones: ["stall", "awning"] },
      { id: "k-baskets", nx: 0.36, ny: 0.44, zones: ["stall", "produce", "basket-zone"] },
    ],
  };

  g.MAP_ORDER = ["village", "park", "forest", "farm", "yard", "market"];
})(window.FBG = window.FBG || {});
